
> chat-service@1.0.0 start
> node server.js

‚ùå Database initialization failed: Error: Access denied for user 'root'@'localhost' (using password: YES)
    at PromisePool.execute (/Users/bhanuprasadkommula/Downloads/Inspectioproject/Backend/chat-service/node_modules/mysql2/lib/promise/pool.js:54:22)
    at initializeDatabase (/Users/bhanuprasadkommula/Downloads/Inspectioproject/Backend/chat-service/server.js:52:26)
    at Object.<anonymous> (/Users/bhanuprasadkommula/Downloads/Inspectioproject/Backend/chat-service/server.js:809:1)
    at Module._compile (node:internal/modules/cjs/loader:1692:14)
    at Object..js (node:internal/modules/cjs/loader:1824:10)
    at Module.load (node:internal/modules/cjs/loader:1427:32)
    at Module._load (node:internal/modules/cjs/loader:1250:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:152:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sql: undefined,
  sqlState: '28000',
  sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)"
}
node:events:485
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8089
    at Server.setupListenHandle [as _listen2] (node:net:1940:16)
    at listenInCluster (node:net:1997:12)
    at Server.listen (node:net:2102:7)
    at /Users/bhanuprasadkommula/Downloads/Inspectioproject/Backend/chat-service/server.js:810:10
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1976:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 8089
}

Node.js v24.4.0
